version: "2"

services:
  web:
    restart: always
    build: ./backend
    image: webworkerimage
    working_dir: /usr/src/app
    expose:
      - "8000"
    links:
      - postgres:postgres
      - redis:redis
      - celeryworker:celeryworker
      - celerybeat:celerybeat
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/static
      - mediadata:/usr/src/app/media
    env_file: .env
    environment:
      DEBUG: 'true'
      VIRTUAL_HOST: 'backend'
    command: /usr/local/bin/gunicorn backend.wsgi:application -w 4 -b 0.0.0.0:8000 --reload --log-level debug
    stdin_open: true
    tty: true
    networks:
      - api-tier
      - back-tier

  node:
    restart: always
    build: ./frontend
    container_name: cookiecutter-node
    command: ["npm", "start"]
    environment:
      VIRTUAL_HOST: 'frontend'
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - "3000"
    stdin_open: true
    tty: true
    networks:
      - front-tier


  nginx:
    restart: always
    build: ./nginx
    container_name: cookiecutter-nginx
    environment:
      REACT_DEFAULT_HOST: 'localhost'
      API_DEFAULT_HOST: 'api.localhost'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/sites-enabled:/etc/nginx
      - /var/run/docker.sock:/tmp/docker.sock:ro
    volumes_from:
      - web
      - node
    depends_on:
      - web
      - node
    links:
      - web
      - node
    networks:
      - front-tier
      - api-tier

  postgres:
    restart: always
    image: postgres:10.7
    container_name: cookiecutter-postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - back-tier

  redis:
    restart: always
    image: redis:latest
    container_name: r-redis
    ports:
      - "6382:6379"
    volumes:
      - redisdata:/data
    networks:
      - back-tier

  celeryworker:
    restart: always
    build: ./backend
    image: webworkerimage
    working_dir: /usr/src/app
    container_name: cookiecutter-celeryworker
    volumes:
      - mediadata:/usr/src/app/media
      - ./backend:/usr/src/app
    env_file: .env
    environment:
      DEBUG: 'true'
      C_FORCE_ROOT: 'yes'
    depends_on:
      - postgres
      - redis
    command: celery worker --app=backend --maxtasksperchild 10 -E --loglevel=DEBUG
    networks:
      - back-tier

  celerybeat:
    restart: always
    build: ./backend
    image: webworkerimage
    working_dir: /usr/src/app
    container_name: cookiecutter-celerybeat
    volumes:
      - /usr/src/app
      - ./backend:/usr/src/app
    env_file: .env
    environment:
      DEBUG: 'true'
      C_FORCE_ROOT: 'yes'
    depends_on:
      - postgres
      - redis
    command: celery beat --app=backend -s /tmp/celerybeat-schedule --pid=/tmp/celery.pid --loglevel=DEBUG
    networks:
      - back-tier

volumes:
  pgdata:
  mediadata:
  redisdata:


networks:
  front-tier:
    driver: bridge
  api-tier:
    driver: bridge
  back-tier:
    driver: bridge
